services:
  postgresql:
    container_name: postgresql
    image: ghcr.io/xudongcc/postgresql:${POSTGRESQL_VERSION}
    restart: always
    ports:
      - ${POSTGRESQL_HOST}:${POSTGRESQL_PORT}:5432
    volumes:
      - ./postgresql/data:/bitnami/postgresql/data
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pgaudit,pg_stat_statements,pg_partman_bgw

  redis:
    container_name: redis
    image: bitnami/redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
